### PR TITLE
remove references to the now delete linkml_runtime.utils.ifabsent_functions

### PR DESCRIPTION
**Pull request by vincentkelleher**
This pull-request is necessary for https://github.com/linkml/linkml/pull/2175 as the documentation and metadata has been modified by the fact the `linkml_runtime.utils.ifabsent_functions` have been deleted.

The new enum default value support has also been documented in this pull-request.

### CODE REVIEW

**Comment by vincentkelleher** [comment]
I'm getting the rate limiting issue with coverage again.

image

I've disabled the Github CI fail in the case where coverage upload fails to see if it works.

**Comment by vincentkelleher** [comment]
> I'm getting the rate limiting issue with coverage again.
> 
> image
> 
> I've disabled the Github CI fail in the case where coverage upload fails to see if it works.

And it works 😅

**Review by cmungall — CHANGES_REQUESTED** [review]
Thanks @vincentkelleher!

The process for modifying the metadata is a little more involved.

Can you make the PR to this file? https://github.com/linkml/linkml-model/blob/main/linkml_model/model/schema/meta.yaml

We will then take care of propagating the changes back through the copy in runtime

**Comment by vincentkelleher** [comment]
Hi @cmungall 

Could you explain to me what the next steps are now that my pull request on the `linkml-model` project is validated ? 😇

**Comment by vincentkelleher** [comment]
Just rebased this branch to include the latest updates from `linkml-model:1.8.0` 😉

**Review by cmungall — APPROVED** [review]

**Pull request merged**
