### PR TITLE
load_source should return lists when lists are passed

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by hsolbrig** [comment]
Is there a unit test?  How do we know whether it worked?

**Review by hsolbrig — APPROVED** [review]
Happy to merge, but note that if the code breaks, we'll never know...

**Comment by cmungall** [comment]
Will add tests

Fixes https://github.com/linkml/linkml/issues/589

**Comment by cmungall** [comment]
Tests added!

**Pull request merged**
