### PR TITLE
Bump pydantic requirement 

### PR DESCRIPTION
**Pull request by caufieldjh**
I'm trying to work with [llm](https://github.com/simonw/llm) in OntoGPT, but it requires `pydantic>=2.0.0`. 
Linkml-runtime currently requires `pydantic (>=1.10.2,<2.0.0)`.

Loosening the requirement to allow pydantic of >=2 installs pydantic 1.10.7 (on Py3.9, at least) but also appears to pass tests.
Mandating pydantic >=2 installs 2.1.1. This means some differences in model definition (e.g., define params to pass to new model objects with `__signature__ attribute`) but all tests pass after accounting for that.

### CODE REVIEW

**Comment by caufieldjh** [comment]
Traces on the erroring tests:
```
ERROR: tests.test_loaders_dumpers.test_dumpers_pydantic (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_loaders_dumpers.test_dumpers_pydantic
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/linkml-runtime/linkml-runtime/tests/test_loaders_dumpers/test_dumpers_pydantic.py", line 7, in <module>
    from tests.test_loaders_dumpers.models.books_normalized_pydantic import Book, BookSeries, Author
  File "/home/runner/work/linkml-runtime/linkml-runtime/tests/test_loaders_dumpers/models/books_normalized_pydantic.py", line 21, in <module>
    use_enum_values = True):
  File "/home/runner/.cache/pypoetry/virtualenvs/linkml-runtime-M8KxIAsy-py3.7/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 123, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: __init_subclass__() takes no keyword arguments


======================================================================
ERROR: tests.test_loaders_dumpers.test_loaders_pydantic (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_loaders_dumpers.test_loaders_pydantic
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/linkml-runtime/linkml-runtime/tests/test_loaders_dumpers/test_loaders_pydantic.py", line 6, in <module>
    from tests.test_loaders_dumpers.models.books_normalized_pydantic import BookSeries
  File "/home/runner/work/linkml-runtime/linkml-runtime/tests/test_loaders_dumpers/models/books_normalized_pydantic.py", line 21, in <module>
    use_enum_values = True):
  File "/home/runner/.cache/pypoetry/virtualenvs/linkml-runtime-M8KxIAsy-py3.7/lib/python3.7/site-packages/pydantic/_internal/_model_construction.py", line 123, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: __init_subclass__() takes no keyword arguments
```

**Review by pkalita-lbl — COMMENTED** [review]
I'm concerned about the downstream effects of this. Requiring `pydantic >= 2.0.0` here means that eventually `linkml` itself will inherit that requirement and then any project that depends on `linkml` as well. Since the Pydantic generator in `linkml` currently only generates Pydantic 1.x models I'm sure there are lots of projects out there that rely on both `linkml` and `pydantic == 1.*`

Maybe we can take a look at this together and figure out a way to be compatible with both Pydantic 1 and 2.

**Comment by pkalita-lbl** [comment]
@caufieldjh I pushed a change that updates the `pyproject.toml` file to indicate that `linkml-runtime` is compatible in _downstream_ projects with either Pydantic 1 or 2. But I left the `poetry.lock` file as-is so that we get Pydantic 2 in _this_ project's environment (and compatible with your test changes).

**Comment by caufieldjh** [comment]
Works for me!

**Review by pkalita-lbl — APPROVED** [review]

**Pull request merged**
