### PR TITLE
Fix signature issue in previous issue_76 fix.

### PR DESCRIPTION
**Pull request by hsolbrig**
Also update the publish action to correctly update the
AUTHORS and ChangeLog

### CODE REVIEW

**Comment by hsolbrig** [comment]
I have no idea what is going on with the python 3.10 in the unit tests.  It works locally, so the only difference I can come up with is that I'm using 3.10.1 and github's latest is still 3.10.0.  Hopefully this will resolve itself in due time?

**Comment by sujaypatil96** [comment]
@hsolbrig: there was increasing advocacy to integrate and use [poetry](https://python-poetry.org/docs/) rather than setuptools with pbr within the group. So the current version of the `main` branch supports build and distribution of the package with poetry.

In the process I also updated the [pypi-publish.yaml](https://github.com/linkml/linkml-runtime/blob/main/.github/workflows/pypi-publish.yaml) workflow to publish the package with poetry commands. setuptools is being deprecated in PR #91. So one of the side effects of setuptools being deprecated is that pbr will be deprecated as well. And since we won't have pbr, we won't have the automated updation of AUTHORS and ChangeLog. Do you have any ideas to circumvent this?

**Comment by cmungall** [comment]
@sujaypatil96 can you make a new PR with the equivalnt changes?

**Comment by sujaypatil96** [comment]
Left a comment on issue #76.

**Pull request closed without merging**
